_wandb:
    value:
        cli_version: 0.24.0
        e:
            ynykpjnj56jyqja1nnsyvbp8zlatdnex:
                args:
                    - --csv
                    - .\tournament.csv
                    - --raw
                    - .\results.txt
                    - --project
                    - CS4880-PA3
                    - --run-name
                    - AdaptiveRushBot-fast
                codePath: Assignment 3\resultsWandB.py
                codePathLocal: resultsWandB.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511264681984"
                        used: "276661010432"
                email: pr881922@ohio.edu
                executable: C:\Users\prigg\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                git:
                    commit: 65c825961f7b4988789c2d224cd8e7fc6fbfdcff
                    remote: https://github.com/parker-riggs/CS4880.git
                host: DESKTOP-HBPM37U
                memory:
                    total: "12163739648"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\prigg\OneDrive\Documents\GitHub\CS4880\Assignment 3\resultsWandB.py
                python: CPython 3.13.12
                root: C:\Users\prigg\OneDrive\Documents\GitHub\CS4880\Assignment 3
                startedAt: "2026-02-19T19:22:37.358719Z"
                writerId: ynykpjnj56jyqja1nnsyvbp8zlatdnex
        m: []
        python_version: 3.13.12
        t:
            "3":
                - 13
                - 15
                - 16
            "4": 3.13.12
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
bot:
    value: AdaptiveRushBot
source_csv:
    value: C:\Users\prigg\OneDrive\Documents\GitHub\CS4880\Assignment 3\tournament.csv
source_raw_results:
    value: C:\Users\prigg\OneDrive\Documents\GitHub\CS4880\Assignment 3\results.txt
