_wandb:
    value:
        cli_version: 0.24.0
        e:
            zz9vx7mev7xpi4vysayep64nnv1qt8uf:
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511264681984"
                        used: "276669894656"
                email: pr881922@ohio.edu
                executable: C:\Users\prigg\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                git:
                    commit: 65c825961f7b4988789c2d224cd8e7fc6fbfdcff
                    remote: https://github.com/parker-riggs/CS4880.git
                host: DESKTOP-HBPM37U
                memory:
                    total: "12163739648"
                os: Windows-10-10.0.19045-SP0
                program: <python with no main file>
                python: CPython 3.13.12
                root: C:\Users\prigg\OneDrive\Documents\GitHub\CS4880\Assignment 3
                startedAt: "2026-02-19T19:26:01.210519Z"
                writerId: zz9vx7mev7xpi4vysayep64nnv1qt8uf
        m: []
        python_version: 3.13.12
        t:
            "3":
                - 2
                - 13
            "4": 3.13.12
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
